/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hja.grupo3.practica3_hja.view;

import hja.grupo3.practica3_hja.game.Board;
import hja.grupo3.practica3_hja.game.Card;
import hja.grupo3.practica3_hja.game.Player;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Usuario
 */
public class BoardViewer extends javax.swing.JFrame {

    /**
     * Creates new form BoardViewer
     */
    
    private static final int FINAL_NUMBER_CARDS = 4; // Contando desde 0
    private static final int EMPTY_BOARD= 0; // Hay 0 cartas en el board
    private static final int INITIAL_NUMBER_CARDS = 3; // Contando desde 0
    private Board board;
    private int numJugadores;
    private Player[] players;
    private Card[] commonCards;
    private int contTable;
    private boolean omaha;
    private cartasPanel[] lista;
    private cartasPanel cartasBoardPanel;
    
    public BoardViewer() {
        initComponents();
        setVisible(true);
        this.setLocationRelativeTo(null);
    }
    
    public BoardViewer(Board board, int numJugadores, Player[] players, Card[] commonCards) {
        
        //-----CONSTRUCTOR----
        this.board = board;
        this.contTable = 0;
        this.lista = new cartasPanel[players.length];
  
        this.omaha = this.board.getOmaha();
        if (omaha) { this.board.equityOmaha(0);}
        else { this.board.equity(0); }
        this.numJugadores = numJugadores;
        this.players = players;
        this.commonCards = commonCards;
        initComponents();
        setVisible(true);
        this.setLocationRelativeTo(null);
        
        //------FONDO------------
        BackGroundPanel panelFondo = new BackGroundPanel();
        this.setContentPane(panelFondo);
        
        //-------CARTAS-----------
        if (players != null){
            dibujarCartasJugadores();
            dibujarCartasMesa();
        }
       
        getContentPane().add(nextButton);
        getContentPane().add(backButton);
        
        
    }
    
    public void dibujarCartasMesa(){
        int X = this.getWidth() / 3 - 20;
        int Y = this.getHeight() / 3 + 40;
        this.cartasBoardPanel = new cartasPanel(this,"",commonCards, 0, false);
        this.cartasBoardPanel.setBounds(X, Y, 400,225); 
        getContentPane().add(cartasBoardPanel);
    }
    
     public void dibujarCartasJugadores(){
        int centroX = (this.getWidth() / 3)+ 60;
        int centroY = (this.getHeight() / 3);
        double radioX = 400; // Radio horizontal del óvalo
        double radioY = 250; // Radio vertical del óvalo
           
        double angulo = 2 * Math.PI / numJugadores;
         for (int i = 0; i < numJugadores; i++) {
            cartasPanel cartasPanel = new cartasPanel(this,players[i].getID(), players[i].getCards(), players[i].getEquity(),omaha);
            double x = centroX + radioX * Math.cos(i * angulo) - cartasPanel.getWidth() / 2;
            double y = centroY + radioY * Math.sin(i * angulo) - cartasPanel.getHeight() / 2;
            if(omaha) {
                cartasPanel.setBounds((int) x, (int) y - 30, 200, 320); 
            }
            else {
                cartasPanel.setBounds((int) x, (int) y, 200, 225); 
            }
             lista[i] = cartasPanel;
             getContentPane().add(cartasPanel);
        }  
    }
     
    public void addCard(Card[] card){
        for ( int i = 0; i < card.length; i++){
            board.addCard(card[i]);
        }
    }
    
    public void foldPlayer(String id) {
          board.foldPlayer(id);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nextButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1132, 800));

        nextButton.setBackground(new java.awt.Color(153, 0, 0));
        nextButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nextButton.setForeground(new java.awt.Color(255, 255, 255));
        nextButton.setText("NEXT");
        nextButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(153, 0, 0));
        backButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("BACK");
        backButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        backButton.setOpaque(true);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(929, Short.MAX_VALUE)
                .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 418, Short.MAX_VALUE)
                .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
       
        if ( contTable == FINAL_NUMBER_CARDS){
            nextButton.setEnabled(false);
        }
       
        if (contTable == EMPTY_BOARD){
           setContTable(INITIAL_NUMBER_CARDS);
            board.nextCard(this.contTable);
        }
        else{
            setContTable(this.contTable + 1);
            board.nextCard(this.contTable);
        }
        
        if (omaha) { board.equityOmaha(this.contTable); }
        else { board.equity(this.contTable); }
        
        this.commonCards = board.getNextCards();
        actualizarGUI();
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_nextButtonActionPerformed

     public void setContTable(int x){
        this.contTable = x;
    }
    public void actualizarGUI(){
        getContentPane().remove(cartasBoardPanel);
        dibujarCartasMesa();
        actualizarCartasJugadores();
        getContentPane().revalidate();
        getContentPane().repaint();
    }
     private void actualizarCartasJugadores() {
         for ( int i = 0; i < players.length; i++){
                lista[i].setEquity(players[i].getEquity());
                lista[i].actualizarEquity();
    }
       
    }
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        MainWindow mainWindow = new MainWindow(board);
        mainWindow.setVisible(true);
        board.resetBoardCard();
        board.resetCard();
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BoardViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BoardViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BoardViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BoardViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BoardViewer().setVisible(true);
            }
        });
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton nextButton;
    // End of variables declaration//GEN-END:variables

    void equity() {
        this.players = board.getPlayers();
        board.equity(this.contTable);
        if (omaha) { board.equityOmaha(this.contTable); }
        else { board.equity(this.contTable); }
    }
    
}
