/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hja.grupo3.practica3_hja.view;

import hja.grupo3.practica3_hja.game.Board;
import java.io.File;

/**
 *
 * @author Usuario
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    
    private ChooseCard chooseCard;
    private ChooseCard chooseBoardCard;
    boolean _fileChoosen = false;
    boolean _optionChoosen = false;
    File _mainFile;
    int _option;
    Board board;
    boolean omaha;
    
    boolean cardsPlayers = false;
    boolean cardsCommon = false;
    
    public MainWindow() {}

    public MainWindow(Board board) {
        this.chooseCard = new ChooseCard();
        this.chooseBoardCard = new ChooseCard();
        initComponents();
        setVisible(true);
        this.setLocationRelativeTo(null);
        this.board = board;
        this.omaha = board.getOmaha();
        
    }
    
    public void setPlayEnable(boolean x){
        this.playButton.setEnabled(x);
    }
     public void setCardsCommon(boolean x){
        this.cardsCommon= x;
    }
     public void setCardsPlayers(boolean x){
        this.cardsPlayers= x;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        aleatorioButton = new javax.swing.JButton();
        chooseButton = new javax.swing.JButton();
        playersLabel = new javax.swing.JLabel();
        boardLabel = new javax.swing.JLabel();
        randomBoardButton = new javax.swing.JButton();
        chooseBoardButton = new javax.swing.JButton();
        playButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));

        titleLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/poker.jpg"))); // NOI18N

        aleatorioButton.setBackground(new java.awt.Color(204, 255, 204));
        aleatorioButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        aleatorioButton.setText("RANDOM CARDS");
        aleatorioButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        aleatorioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aleatorioButtonActionPerformed(evt);
            }
        });

        chooseButton.setBackground(new java.awt.Color(255, 153, 153));
        chooseButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chooseButton.setText("CHOOSE CARDS");
        chooseButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chooseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseButtonActionPerformed(evt);
            }
        });

        playersLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        playersLabel.setText("Select card for the players: ");

        boardLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        boardLabel.setText("Select card for the board: ");

        randomBoardButton.setBackground(new java.awt.Color(204, 255, 204));
        randomBoardButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        randomBoardButton.setText("RANDOM CARDS");
        randomBoardButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        randomBoardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomBoardButtonActionPerformed(evt);
            }
        });

        chooseBoardButton.setBackground(new java.awt.Color(255, 153, 153));
        chooseBoardButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chooseBoardButton.setText("CHOOSE CARDS");
        chooseBoardButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chooseBoardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseBoardButtonActionPerformed(evt);
            }
        });

        playButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/playIcon.png"))); // NOI18N
        playButton.setEnabled(false);
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boardLabel)
                            .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MainPanelLayout.createSequentialGroup()
                                    .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(aleatorioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(randomBoardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(42, 42, 42)
                                    .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(chooseButton, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                        .addComponent(chooseBoardButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(MainPanelLayout.createSequentialGroup()
                                    .addComponent(playersLabel)
                                    .addGap(206, 206, 206)))))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(playButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playersLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aleatorioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(boardLabel)
                .addGap(18, 18, 18)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(randomBoardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseBoardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(playButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aleatorioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aleatorioButtonActionPerformed
        board.resetCard();
        playButton.setEnabled(false);
        if(omaha) {
            board.randomCards(4);
        }
        else { board.randomCards(2);}
        cardsPlayers = true;
        //chooseButton.setEnabled(false);
        //aleatorioButton.setEnabled(false);
        if (cardsPlayers && cardsCommon) playButton.setEnabled(true);
    }//GEN-LAST:event_aleatorioButtonActionPerformed

    private void chooseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseButtonActionPerformed
        board.resetCard();
        playButton.setEnabled(false);
        if(omaha) {
            chooseCard = new ChooseCard(this,board,4);
        }
        else {
            chooseCard = new ChooseCard(this,board,2);
        }
        cardsPlayers = true;
        //aleatorioButton.setEnabled(false);
        //chooseButton.setEnabled(false);
        if (cardsPlayers && cardsCommon) playButton.setEnabled(true);
    }//GEN-LAST:event_chooseButtonActionPerformed

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        BoardViewer boardViewer = new BoardViewer(board, 6,board.getPlayers(),board.getNextCards());  
        this.dispose();
    }//GEN-LAST:event_playButtonActionPerformed

    private void chooseBoardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseBoardButtonActionPerformed
        board.resetBoardCard();
        playButton.setEnabled(false);
        chooseBoardCard = new ChooseCard(this,board,5);
        cardsCommon = true;
        //chooseBoardButton.setEnabled(false);
       // randomBoardButton.setEnabled(false);
        if (cardsPlayers && cardsCommon) playButton.setEnabled(true);        
    }//GEN-LAST:event_chooseBoardButtonActionPerformed

    private void randomBoardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomBoardButtonActionPerformed
        board.resetBoardCard();
        playButton.setEnabled(false);
        board.randomBoardCards();
        cardsCommon = true;
        //chooseBoardButton.setEnabled(false);
        //randomBoardButton.setEnabled(false);
        if (cardsPlayers && cardsCommon) playButton.setEnabled(true);        
    }//GEN-LAST:event_randomBoardButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton aleatorioButton;
    private javax.swing.JLabel boardLabel;
    private javax.swing.JButton chooseBoardButton;
    private javax.swing.JButton chooseButton;
    private javax.swing.JButton playButton;
    private javax.swing.JLabel playersLabel;
    private javax.swing.JButton randomBoardButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
